<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Game</title>
  <style>
    /* 전체 HTML, body 기본 스타일 */
    html, body {
      margin: 0;
      padding: 0;
      width: 100%;
      height: 100%;
      display: flex;
      justify-content: center;
      align-items: center;
      background: linear-gradient(to bottom, #2c3e50, #bdc3c7); /* 부드러운 배경 색상 */
      color: white;
      font-family: 'Arial', sans-serif;
      overflow: hidden;
    }

    /* 게임 시작 버튼 스타일 */
    #startButton {
      padding: 15px 30px;
      font-size: 20px;
      background-color: #3498db; /* 파란색 */
      color: white;
      border: none;
      border-radius: 10px;
      cursor: pointer;
      box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.3);
      transition: all 0.3s ease;
    }

    #startButton:hover {
      background-color: #2980b9; /* 더 어두운 파란색 */
      transform: scale(1.05); /* 약간 확대 */
    }

    #startButton:active {
      background-color: #1c5985; /* 더 진한 파란색 */
      transform: scale(0.95); /* 살짝 축소 */
    }

    /* 게임 캔버스 */
    #gameCanvas {
      display: none; /* 초기에는 숨김 */
      position: absolute;
      top: 0;
      left: 0;
    }
  </style>
</head>
<body>
  <!-- 게임 시작 버튼 -->
  <button id="startButton">게임 시작</button>

  <!-- 캔버스 (게임 화면) -->
  <canvas id="gameCanvas"></canvas>

  <!-- 게임 스크립트 -->
  <script src="game.js"></script>
</body>
</html>
